;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        cycle-spacing
        forward-sexp
        smart-hungry-delete-forward-char
        ))

(setq mc/cmds-to-run-once
      '(
        hydra-multiple-cursors/mc/mark-next-like-this
        ))
